# Generated by Django 5.0.6 on 2024-06-11 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chefe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api_rest.departamento'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.curso')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos_matriculados',
            field=models.ManyToManyField(related_name='alunos', through='api_rest.Matricula', to='api_rest.curso'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('especialidade', models.CharField(max_length=200)),
                ('cursos', models.ManyToManyField(related_name='professores', through='api_rest.Alocacao', to='api_rest.curso')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='professores',
            field=models.ManyToManyField(related_name='departamentos', to='api_rest.professor'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.professor'),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.CharField(max_length=10)),
                ('localizacao', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('cursos', models.ManyToManyField(through='api_rest.CursoSala', to='api_rest.curso')),
            ],
        ),
        migrations.AddField(
            model_name='cursosala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.sala'),
        ),
        migrations.AddField(
            model_name='curso',
            name='salas',
            field=models.ManyToManyField(through='api_rest.CursoSala', to='api_rest.sala'),
        ),
    ]
